#:kivy 2.1.0

<Folder>:    
    canvas:
        Color:
            rgba: 55,49,52,0.58
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        id: 'drive'
        text: 'Hello World'
        text_size: self.size
        halign: 'right'
        valign: 'middle'

<address_bar>:
    TextInput:
        font_size:15
        size_hint_y:None
        height:30
        multiline:False
        valign: 'top'

    